#!/usr/bin/env bash

set -euo pipefail
set -x

# stash script -- https://gist.github.com/steve-jansen/5117721
stash() {
  # check if we have uncommitted changes to stash
  git status --porcelain | grep "^." >/dev/null;

  if [[ $? -eq 0 ]]
  then
    if git stash save -u "git-update on `date`";
    then
      stash=1;
    fi
  fi
}

unstash() {
  # check if we have uncommitted change to restore from the stash
  if [[ $stash -eq 1 ]]
  then
    git stash pop;
  fi
}

if [[ ${BUILDKITE_COMMAND_EXIT_STATUS:-0} != "0" ]]
then
  echo "--- Skipping git-commit because the command failed"
  exit 0
fi

add_path=${BUILDKITE_PLUGIN_GIT_COMMIT_ADD:-}
create_branch=${BUILDKITE_PLUGIN_GIT_COMMIT_CREATE_BRANCH:-false}
remote=${BUILDKITE_PLUGIN_GIT_COMMIT_REMOTE:-origin}
branch=${BUILDKITE_PLUGIN_GIT_COMMIT_BRANCH:-${BUILDKITE_BRANCH}}
commitmessage=${BUILDKITE_PLUGIN_GIT_COMMIT_MESSAGE:-"Build #${BUILDKITE_BUILD_NUMBER}"}
tag=${BUILDKITE_PLUGIN_GIT_COMMIT_TAG:-}
tagmessage=${BUILDKITE_PLUGIN_GIT_COMMIT_TAG_MESSAGE:-"Build #${BUILDKITE_BUILD_NUMBER}"}
user_name=${BUILDKITE_PLUGIN_GIT_COMMIT_USER_NAME:-Buildkite CI}
user_email=${BUILDKITE_PLUGIN_GIT_COMMIT_USER_EMAIL:-sre-team@quantopian.com}

git config user.name "$user_name"
git config user.email "$user_email"

if [[ "$create_branch" == "true" ]]; then
  git checkout -b "${branch}"
else
  git fetch "${remote}" "${branch}:${branch}"
  stash=0;
  stash;
  git checkout "${branch}"
  unstash;
fi

# Add commits
if [[ -n "$add_path" ]]; then
  git add -A "$add_path"

  if ! git diff-index --quiet HEAD; then
    echo "--- Committing changes"
    git commit -m "${commitmessage}"

    echo "--- Pushing ${branch} to ${remote}"
    git push "${remote}" "${branch}"
  else
    echo "--- No changes to commit"
  fi
fi

# Add tag
if [[ -n "$tag" ]]; then
  echo "--- Tagging with $tag"
  git tag -f -a $tag -m "$tagmessage"

  echo "--- Pushing tag to ${remote}"
  git push -f ${remote} --tags "$tag"
else
  echo "--- No tags to push"
fi
